modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="too_much_bosses"
version="1.0.0"
displayName="Too Much Bosses"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Cookie5w, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.too_much_bosses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



